version: '2.0'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
     image: wurstmeister/kafka
     links:
       - zookeeper:zk
     ports:
       - "9092:9092"
     environment:
       KAFKA_ADVERTISED_HOST_NAME: $CF_HOST_IP
       KAFKA_ZOOKEEPER_CONNECT: zk:2181
       KAFKA_MESSAGE_MAX_BYTES: 2000000
       KAFKA_CREATE_TOPICS: "Topic1:1:1"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
     depends_on:
       - zookeeper
  psql:
    build: db/
    depends_on:
      - kafka
  appjava:
    build: client\build\docker
    ports:
      - '8080:8080'
    links:
      - psql:database
    depends_on:
      - psql
